query_1 = "CREATE TABLE Readers (id serial PRIMARY KEY, name VARCHAR(60), email VARCHAR(60), iss_active bool)"
query_2 = "CREATE TABLE Publishinghouses (id serial PRIMARY KEY, name VARCHAR(60), city VARCHAR(20), adress VARCHAR(120))"
query_3 = "CREATE TABLE Books (id serial PRIMARY KEY, title VARCHAR(60), price DECIMAL(5, 2), author VARCHAR(60), publishing_houses_id INT)"
query_4 = "CREATE TABLE ReadersBooks (id serial, Readers_id INTEGER, PRIMARY KEY(id), FOREIGN KEY(Readers_id) REFERENCES Readers(id), FOREIGN KEY(Books_id) REFERENCES Books(id));)"
query_5 = "SELECT * FROM Items WHERE Items.price>10;"
query_6 = "INSERT INTO Publishinghouses(name, city, adress) VALUES('Super Książki', 'Kaczy Dół', 'Batorego 120');"
query_7 = "DELETE FROM Books WHERE id=12;"
query_8 = "SELECT * FROM ReadersBooks WHERE Items.price>10;"
query_9 = ""
query_10 = "ALTER TABLE Readers ADD date_of_birth INT;"
